$(document).ready(function(){
    $(".swords").click(function(){
      $(".firstsword").toggleClass("open1");
    });
  });
  $(document).ready(function(){
    $(".swords").click(function(){
      $(".secondsword").toggleClass("open2");
    });
  });
  $(document).ready(function(){
    $(".swords").click(function(){
      $(".thirdsword").toggleClass("open3");
    });
  });
  $(document).ready(function(){
    $(".swords").click(function(){
      $(".vader").toggleClass("openvader");
    });
  });
  $(document).ready(function(){
    $(".balls").click(function(){
      $(".newtonspendulum").toggleClass("skywalker");
    });
  });